services:
  notifier:
    build: ./notifier
    container_name: notifier
    environment:
      - NODE_ENV=production
    networks:
      - backend-net
    ports:
      - "5000:5000"

  processor1:
    build: ./processor
    container_name: processor1
    depends_on:
      - notifier
    environment:
      - NODE_ENV=production
      - NOTIFIER_URL=http://notifier:5000/notify
    networks:
      - backend-net

  processor2:
    build: ./processor
    container_name: processor2
    depends_on:
      - notifier
    environment:
      - NODE_ENV=production
      - NOTIFIER_URL=http://notifier:5000/notify
    networks:
      - backend-net

  processor3:
    build: ./processor
    container_name: processor3
    depends_on:
      - notifier
    environment:
      - NODE_ENV=production
      - NOTIFIER_URL=http://notifier:5000/notify
    networks:
      - backend-net

  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    depends_on:
      - processor1
      - processor2
      - processor3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    networks:
      - backend-net

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - nginx
      - notifier
    environment:
      - PROCESSOR_URL=http://nginx:8080/process
      - NOTIFIER_URL=http://notifier:5000/notify
    ports:
      - "3000:3000"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

